### ISSUE TITLE
安装环境失败

### ISSUE THREAD

**Issue by wwbnjsace** [Le-Xiaohuai-speech/DPCRN_DNS3#42]
你好，你们的安装环境是什么，我在tf1.15和1.14下面一直报错，失败，按照require的要求来安装也一直识别，有具体详细的环境包版本要求吗

2024-11-21 13:58:07.918952: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2024-11-21 13:58:07.947772: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3187200000 Hz
2024-11-21 13:58:07.948298: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x321d0e20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-11-21 13:58:07.948311: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "main.py", line 486, in <module>
    model = dpcrn.build_DPCRN_model()
  File "main.py", line 291, in build_DPCRN_model
    dp_in = DprnnBlock(numUnits = self.numUnits, batch_size = self.batch_size, L = -1,width = 50,channel = 128, causal=True)(dp_in)#self.DPRNN_kernal(dp_in,str(i),last_dp = 0)
  File "/home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 849, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in converted code:

    /data/DPCRN_DNS3-main/modules.py:70 call  *
        intra_LSTM_out = intra_rnn(intra_LSTM_input)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/wrappers.py:528 __call__
        return super(Bidirectional, self).__call__(inputs, **kwargs)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:849 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/wrappers.py:642 call
        initial_state=forward_state, **kwargs)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:623 __call__
        return super(RNN, self).__call__(inputs, **kwargs)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:849 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:2549 call
        inputs, mask=mask, training=training, initial_state=initial_state)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:682 call
        inputs, initial_state, constants)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:798 _process_inputs
        initial_state = self.get_initial_state(inputs)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:606 get_initial_state
        inputs=None, batch_size=batch_size, dtype=dtype)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:2314 get_initial_state
        self, inputs, batch_size, dtype))
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:2752 _generate_zero_filled_state_for_cell
        return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:2768 _generate_zero_filled_state
        return nest.map_structure(create_zeros, state_size)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py:536 map_structure
        structure[0], [func(*x) for x in entries],
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py:536 <listcomp>
        structure[0], [func(*x) for x in entries],
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:2765 create_zeros
        return array_ops.zeros(init_state_size, dtype=dtype)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py:2338 zeros
        output = _constant_if_small(zero, shape, dtype, name)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py:2295 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:6 prod
        
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3052 prod
        keepdims=keepdims, initial=initial, where=where)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    /home/ns/miniconda3/envs/dpcrn37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:736 __array__
        " array.".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (dprnn_block/bidirectional/forward_lstm/strided_slice:0) to a numpy array.

**Comment by 0211maxinhao** [comment]
哈喽，
这个问题解决了嘛，我尝试运行项目也遇到同样的问题。 @wwbnjsace
